version: "3.8"
services:
  backend_sample_app:
    image: backend_sample_app:latest
    container_name: backend_sample_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    env_file: ./src/configs/.env.development
    environment:
      - DOCKER_ENV=true
  mongo_db:
    # Defines the service for the MongoDB database
    image: mongo # Uses the official MongoDB image from Docker Hub
    ports:
      - "27017:27017" # Maps port 27017 in the container to port 27017 on the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: sunteangg # Sets the root username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: myp4ssw0rd # Sets the root password for MongoDB
      MONGO_INITDB_ROOT_DATABASE: myProducts # Specifies the initial database to create
    volumes:
      - mongo_data:/data/db # Persists MongoDB data using a named volume

volumes:
  mongo_data: # Defines a named volume for MongoDB data persistence

